development: &default
  adapter: postgresql
  encoding: unicode
  database: myapp_development
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV['DBHOST'] %>
  username: <%= ENV['DBUSER'] %>
  password: <%= ENV['DBPASS'] %>
  template: 'template0'

test:
  <<: *default
  database: myapp_test
